import { makeStyles } from '@material-ui/core/styles';

export default makeStyles(theme => (
    {
        root: {
            flexGrow: 1,
            margin: theme.spacing(1),
            padding: theme.spacing(1),
            textAlign: 'center',
            backgroundColor: 'rgb(206, 213, 223)',
            height: '400px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 'calc(10px + 2vmin)',
        },
        card: {
            backgroundColor: 'white',
            padding: '15px',
            width: '100%',
            display: 'flex',
            alignItems: 'flex-start',
            justifyContent: 'flex-start',
            boxShadow: '0 15px 30px 0 rgba(0, 0, 0, 0.11), 0 5px 15px 0 rgba(0, 0, 0, 0.08)',
            boxSizing: 'border-box',
        },
        upload: {
            display: 'flex',
            flexDirection: 'column',
            flex: 1,
            alignItems: 'flex-start',
            textAlign: 'left',
            overflow: 'hidden',
        },
        content: {
            display: 'flex',
            flexDirection: 'row',
            paddingTop: '10px',
            boxSizing: 'border-box',
            width: '100%',
        },
        files: {
            marginLeft: '10px',
            alignItems: 'flex-start',
            justifyItems: 'flex-start',
            flex: 1,
            overflowY: 'auto',
        },
        fileName: {
            marginBottom: '8px',
            fontSize: '16px',
            color: '#555',
        },
        row: {
            display: 'flex',
            flex: 1,
            flexDirection: 'column',
            justifyContent: 'space-between',
            height: '50px',
            padding: '8px',
            overflow: 'hidden',
            boxSizing: 'border-box',
        },
        actions: {
            display: 'flex',
            flex: 1,
            width: '100%',
            alignItems: 'flex-end',
            flexDirection: 'column',
            marginTop: '15px',
        },
        title: {
            marginBottom: '15px',
            color: '#555',
        },
        progressWrapper: {
            display: 'flex',
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
        },
        checkIcon: {
            opacity: 0.5,
            marginLeft: '32px',
        },
        button: {
            fontFamily: '"Roboto medium", sans-serif',
            fontSize: '14px',
            display: 'inline-block',
            height: '36px',
            minWidth: '88px',
            padding: '6px 16px',
            lineHeight: 1.42857143,
            textAlign: 'center',
            whiteSpace: 'nowrap',
            verticalAlign: 'middle',
            '-ms-touch-action': 'manipulation',
            touchAction: 'manipulation',
            cursor: 'pointer',
            '-webkit-user-select': 'none',
            '-moz-user-select': 'none',
            '-ms-user-select': 'none',
            userSelect: 'none',
            border: 0,
            borderRadius: '2px',
            background: 'rgba(103, 58, 183, 1)',
            color: '#fff',
            outline: 0,
            '&:disabled': {
                background: 'rgb(189, 189, 189)',
                cursor: 'default',
            }
        },
    }
));
