export const ADMINUSERS_SEND_REQUEST = 'ADMINUSERS_SEND_REQUEST';
export const ADMINUSER_SEND_REQUEST = 'ADMINUSER_SEND_REQUEST';
export const ADMINUSERS_RESPONSE_FAILED = "ADMINUSERS_RESPONSE_FAILED";
export const ADMINUSER_RESPONSE_FAILED = "ADMINUSER_RESPONSE_FAILED";

export const ADMINUSERS_GET_ALL_ADMINUSERS = 'ADMINUSERS_GET_ALL_ADMINUSERS';
export const ADMINUSERS_ADD_ADMINUSER = 'ADMINUSERS_ADD_ADMINUSER';
export const ADMINUSERS_UPDATE_ADMINUSER = 'ADMINUSERS_UPDATE_ADMINUSER';
export const ADMINUSERS_DELETE_ADMINUSER = 'ADMINUSERS_DELETE_ADMINUSER';

export const ADMINUSER_GET_ADMINUSER_ITEM = 'ADMINUSER_GET_ADMINUSER_ITEM';
