export const ARCHIVES_SEND_REQUEST = 'ARCHIVES_SEND_REQUEST';
export const ARCHIVE_SEND_REQUEST = 'ARCHIVE_SEND_REQUEST';
export const ARCHIVES_RESPONSE_FAILED = "ARCHIVES_RESPONSE_FAILED";
export const ARCHIVE_RESPONSE_FAILED = "ARCHIVE_RESPONSE_FAILED";

export const ARCHIVES_GET_ALL_ARCHIVES = 'ARCHIVES_GET_ALL_ARCHIVES';
export const ARCHIVES_ADD_ARCHIVE = 'ARCHIVES_ADD_ARCHIVE';
export const ARCHIVES_UPDATE_ARCHIVE = 'ARCHIVES_UPDATE_ARCHIVE';
export const ARCHIVES_DELETE_ARCHIVE = 'ARCHIVES_DELETE_ARCHIVE';

export const ARCHIVE_GET_ARCHIVE_ITEM = 'ARCHIVE_GET_ARCHIVE_ITEM';
export const ARCHIVE_GET_ARCHIVE_ITEM_BY_ITEMNO = 'ARCHIVE_GET_ARCHIVE_ITEM_BY_ITEMNO';

export const ARCHIVES_GET_ARCHIVES_BY_FILTER = 'ARCHIVES_GET_ARCHIVES_BY_FILTER';
export const ARCHIVES_GET_ARCHIVES_BY_SEARCH = 'ARCHIVES_GET_ARCHIVES_BY_SEARCH';
export const ARCHIVES_GET_ARCHIVES_BY_PARENT_ID = 'ARCHIVES_GET_ARCHIVES_BY_PARENT_ID';
