export const CART_SEND_REQUEST = 'CART_SEND_REQUEST';
export const CART_RESPONSE_FAILED = "CART_RESPONSE_FAILED";

export const CART_GET_CART = 'CART_GET_CART';
export const CART_CREATE_CART = 'CART_CREATE_CART';
export const CART_UPDATE_CART = 'CART_UPDATE_CART';
export const CART_DELETE_CART = 'CART_DELETE_CART';
export const CART_CLEAN_CART = 'CART_CLEAN_CART';

export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT';
export const CART_DECREASE_PRODUCT_QUANTITY = 'CART_DECREASE_PRODUCT_QUANTITY';
export const CART_DELETE_PRODUCT = 'CART_DELETE_PRODUCT';
