export const CATEGORIES_SEND_REQUEST = 'CATEGORIES_SEND_REQUEST';
export const CATEGORY_SEND_REQUEST = 'CATEGORY_SEND_REQUEST';
export const CATEGORIES_RESPONSE_FAILED = "CATEGORIES_RESPONSE_FAILED";
export const CATEGORY_RESPONSE_FAILED = "CATEGORY_RESPONSE_FAILED";

export const CATEGORIES_GET_ALL_CATEGORIES = 'CATEGORIES_GET_ALL_CATEGORIES';
export const CATEGORIES_ADD_CATEGORY = 'CATEGORIES_ADD_CATEGORY';
export const CATEGORIES_UPDATE_CATEGORY = 'CATEGORIES_UPDATE_CATEGORY';
export const CATEGORIES_DELETE_CATEGORY = 'CATEGORIES_DELETE_CATEGORY';

export const CATEGORY_GET_CATEGORY_ITEM = 'CATEGORY_GET_CATEGORY_ITEM';

export const CATEGORIES_GET_CATEGORIES_BY_SEARCH = 'CATEGORIES_GET_CATEGORIES_BY_SEARCH';
export const CATEGORIES_GET_CATEGORIES_BY_PARENT_ID = 'CATEGORIES_GET_CATEGORIES_BY_PARENT_ID';
