export const CLOUDINARY_UPLOAD_REQUEST = "CLOUDINARY_UPLOAD_REQUEST";
export const CLOUDINARY_UPLOAD_FAILED = "CLOUDINARY_UPLOAD_FAILED";

export const CLOUDINARY_UPDATE_IMAGE = "CLOUDINARY_UPDATE_IMAGE";
export const CLOUDINARY_DELETE_IMAGE = "CLOUDINARY_DELETE_IMAGE";
