export const COLORS_SEND_REQUEST = 'COLORS_SEND_REQUEST';
export const COLOR_SEND_REQUEST = 'COLOR_SEND_REQUEST';
export const COLORS_RESPONSE_FAILED = "COLORS_RESPONSE_FAILED";
export const COLOR_RESPONSE_FAILED = "COLOR_RESPONSE_FAILED";

export const COLORS_GET_ALL_COLORS = 'COLORS_GET_ALL_COLORS';
export const COLORS_ADD_COLOR = 'COLORS_ADD_COLOR';
export const COLORS_UPDATE_COLOR = 'COLORS_UPDATE_COLOR';
export const COLORS_DELETE_COLOR = 'COLORS_DELETE_COLOR';

export const COLOR_GET_COLOR_ITEM = 'COLOR_GET_COLOR_ITEM';
