export const CURRENCY_CURRENCY_GET_CURRENCY = 'CURRENCY_CURRENCY_GET_CURRENCY';
export const CURRENCY_CURRENCY_REQUEST_FAILED = 'CURRENCY_CURRENCY_REQUEST_FAILED';
export const CURRENCY_CHANGE_CURRENCY = 'CURRENCY_CHANGE_CURRENCY';
