export const GENDERS_SEND_REQUEST = 'GENDERS_SEND_REQUEST';
export const GENDER_SEND_REQUEST = 'GENDER_SEND_REQUEST';
export const GENDERS_RESPONSE_FAILED = "GENDERS_RESPONSE_FAILED";
export const GENDER_RESPONSE_FAILED = "GENDER_RESPONSE_FAILED";

export const GENDERS_GET_ALL_GENDERS = 'GENDERS_GET_ALL_GENDERS';
export const GENDERS_ADD_GENDER = 'GENDERS_ADD_GENDER';
export const GENDERS_UPDATE_GENDER = 'GENDERS_UPDATE_GENDER';
export const GENDERS_DELETE_GENDER = 'GENDERS_DELETE_GENDER';

export const GENDER_GET_GENDER_ITEM = 'GENDER_GET_GENDER_ITEM';
