export const ORDERS_SEND_REQUEST = 'ORDERS_SEND_REQUEST';
export const ORDER_SEND_REQUEST = 'ORDER_SEND_REQUEST';
export const ORDERS_RESPONSE_FAILED = "ORDERS_RESPONSE_FAILED";
export const ORDER_RESPONSE_FAILED = "ORDER_RESPONSE_FAILED";

export const ORDERS_GET_ALL_ORDERS = 'ORDERS_GET_ALL_ORDERS';
export const ORDERS_ADD_ORDER = 'ORDERS_ADD_ORDER';
export const ORDERS_UPDATE_ORDER = 'ORDERS_UPDATE_ORDER';
export const ORDERS_DELETE_ORDER = 'ORDERS_DELETE_ORDER';

export const ORDER_GET_ORDER_ITEM = 'ORDER_GET_ORDER_ITEM';
export const ORDER_GET_ORDER_ITEM_BY_ITEMNO = 'ORDER_GET_ORDER_ITEM_BY_ITEMNO';

export const ORDERS_GET_ORDERS_BY_FILTER = 'ORDERS_GET_ORDERS_BY_FILTER';
export const ORDERS_GET_ORDERS_BY_CUSTOMER_ID = 'ORDERS_GET_ORDERS_BY_CUSTOMER_ID';
