export const PRODUCTS_GALLERY_SEND_REQUEST = 'productsGallery_send_request';
export const PRODUCTS_GALLERY_RESPONSE_FAILED = "productsGallery_response_failed";

export const PRODUCTS_GALLERY_GET_ALL_PRODUCTS_GALLERY = 'productsGallery_get_all_productsGallery';
export const PRODUCTS_GALLERY_ADD_PRODUCT_GALLERY = 'productsGallery_add_productGallery';
export const PRODUCTS_GALLERY_CREATE_PRODUCT_GALLERY = 'productsGallery_create_productGallery';
export const PRODUCTS_GALLERY_UPDATE_PRODUCT_GALLERY = 'productsGallery_update_productGallery';
export const PRODUCTS_GALLERY_LOCAL_UPDATE_PRODUCT_GALLERY = 'productsGallery_local_update_productGallery';
export const PRODUCTS_GALLERY_DELETE_PRODUCT_GALLERY = 'productsGallery_delete_productGallery';
export const PRODUCTS_GALLERY_GET_PRODUCT_GALLERY = 'productsGallery_get_productGallery';