export const PRODUCTS_SEND_REQUEST = 'PRODUCTS_SEND_REQUEST';
export const PRODUCT_SEND_REQUEST = 'PRODUCT_SEND_REQUEST';
export const PRODUCTS_RESPONSE_FAILED = "PRODUCTS_RESPONSE_FAILED";
export const PRODUCT_RESPONSE_FAILED = "PRODUCT_RESPONSE_FAILED";

export const PRODUCTS_GET_ALL_PRODUCTS = 'PRODUCTS_GET_ALL_PRODUCTS';
export const PRODUCTS_ADD_PRODUCT = 'PRODUCTS_ADD_PRODUCT';
export const PRODUCTS_UPDATE_PRODUCT = 'PRODUCTS_UPDATE_PRODUCT';
export const PRODUCTS_DELETE_PRODUCT = 'PRODUCTS_DELETE_PRODUCT';

export const PRODUCT_GET_PRODUCT_ITEM = 'PRODUCT_GET_PRODUCT_ITEM';

export const PRODUCTS_GET_PRODUCTS_BY_SEARCH = 'PRODUCTS_GET_PRODUCTS_BY_SEARCH';
