export const SIZETYPES_SEND_REQUEST = 'SIZETYPES_SEND_REQUEST';
export const SIZETYPE_SEND_REQUEST = 'SIZETYPE_SEND_REQUEST';
export const SIZETYPES_RESPONSE_FAILED = "SIZETYPES_RESPONSE_FAILED";
export const SIZETYPE_RESPONSE_FAILED = "SIZETYPE_RESPONSE_FAILED";

export const SIZETYPES_GET_ALL_SIZETYPES = 'SIZETYPES_GET_ALL_SIZETYPES';
export const SIZETYPES_ADD_SIZETYPE = 'SIZETYPES_ADD_SIZETYPE';
export const SIZETYPES_UPDATE_SIZETYPE = 'SIZETYPES_UPDATE_SIZETYPE';
export const SIZETYPES_DELETE_SIZETYPE = 'SIZETYPES_DELETE_SIZETYPE';

export const SIZETYPE_GET_SIZETYPE_ITEM = 'SIZETYPE_GET_SIZETYPE_ITEM';
