export const SIZES_SEND_REQUEST = 'SIZES_SEND_REQUEST';
export const SIZE_SEND_REQUEST = 'SIZE_SEND_REQUEST';
export const SIZES_RESPONSE_FAILED = "SIZES_RESPONSE_FAILED";
export const SIZE_RESPONSE_FAILED = "SIZE_RESPONSE_FAILED";

export const SIZES_GET_ALL_SIZES = 'SIZES_GET_ALL_SIZES';
export const SIZES_ADD_SIZE = 'SIZES_ADD_SIZE';
export const SIZES_UPDATE_SIZE = 'SIZES_UPDATE_SIZE';
export const SIZES_DELETE_SIZE = 'SIZES_DELETE_SIZE';

export const SIZE_GET_SIZE_ITEM = 'SIZE_GET_SIZE_ITEM';

export const SIZES_GET_SIZES_BY_SEARCH = 'SIZES_GET_SIZES_BY_SEARCH';
export const SIZES_GET_SIZES_BY_PARENT_ID = 'SIZES_GET_SIZES_BY_PARENT_ID';