export const TOPCATS_SEND_REQUEST = 'TOPCATS_SEND_REQUEST';
export const TOPCAT_SEND_REQUEST = 'TOPCAT_SEND_REQUEST';
export const TOPCATS_RESPONSE_FAILED = "TOPCATS_RESPONSE_FAILED";
export const TOPCAT_RESPONSE_FAILED = "TOPCAT_RESPONSE_FAILED";

export const TOPCATS_GET_ALL_TOPCATS = 'TOPCATS_GET_ALL_TOPCATS';
export const TOPCATS_ADD_TOPCAT = 'TOPCATS_ADD_TOPCAT';
export const TOPCATS_UPDATE_TOPCAT = 'TOPCATS_UPDATE_TOPCAT';
export const TOPCATS_DELETE_TOPCAT = 'TOPCATS_DELETE_TOPCAT';

export const TOPCAT_GET_TOPCAT_ITEM = 'TOPCAT_GET_TOPCAT_ITEM';
