export const USERS_SEND_REQUEST = 'USERS_SEND_REQUEST';
export const USER_SEND_REQUEST = 'USER_SEND_REQUEST';
export const USERS_RESPONSE_FAILED = "USERS_RESPONSE_FAILED";
export const USER_RESPONSE_FAILED = "USER_RESPONSE_FAILED";

export const USERS_GET_ALL_USERS = 'USERS_GET_ALL_USERS';
export const USERS_ADD_USER = 'USERS_ADD_USER';
export const USERS_UPDATE_USER = 'USERS_UPDATE_USER';
export const USERS_DELETE_USER = 'USERS_DELETE_USER';

export const USER_GET_USER_ITEM = 'USER_GET_USER_ITEM';
